### ISSUE TITLE
Phrase Query behavior

### ISSUE THREAD

**Issue by gmourier** [meilisearch/milli#208]
I have just tested the Phrase Query syntax on an updated 0.21 build and I have behaviors that seem unwanted. I can provide the dataset used if needed to reproduce the tests! Thanks!

# Tests Phrase Query

## Test case 1: Case sensivity

> "q": "\"the four seasons: Poems\""

### Results

```
"hits": [
    {
        "title": "The Four Seasons: Poems",
        "author": "J. D. McClatchy"
    }
]
```

### case 2.1

> "q": "\"African American Literature\"" OR "q": "\"African-American Literature\""

### Results
Same results for the 2 queries
```
{
    "title": "African American Literature (Penguin Academics Series)",
    "author": "Keith Gilyard"
},
{
    "title": "African-American Literature: A Brief Introduction and Anthology",
    "author": "Al Young"
},
{
    "title": "A Companion to African American Literature",
    "author": "Gene A. Jarrett"
}
```

### case 2.2
> "q": "\"the Four Seasons::: Poems\""

### Results
```
"hits": [
    {
        "title": "The Four Seasons: Poems",
        "author": "J. D. McClatchy"
    }
]
```

## Test case 3: Long query terms
> "q": "\"African American Literature (Penguin Academics Series)\""

Weird case because i have no result besides that title exists
My first guess was because the query was too long. But it's not that because it worked with a long title on another document.
My guess is that's because of `(`or ) characters.

### Results

None

**Comment by ManyTheFish** [comment]
Hello @gmourier, you are right parenthesis is considered as a hard-separator by milli.
In your document `African American Literature (Penguin Academics Series)` the block `African American Literature` is never considered close to the block `Penguin Academics Series`.
The rule of the phrase search is to search all the phrase words without typo and with a distance of 1 between them (`Phrase(["African", "American", "Literature", "Penguin", "Academics", "Series"])`).
That's why your last example doesn't work.

A possible enhancement could be to split phrases when we encounter an hard separator. 
Transforming: 
`Phrase(["African", "American", "Literature", "Penguin", "Academics", "Series"])`
in `Phrase(["African", "American", "Literature"]), Phrase(["Penguin", "Academics", "Series"])`

the query:
> "q": ""African American Literature (Penguin Academics Series)""

would be considered as the same as:
> "q": ""African American Literature" "Penguin Academics Series""

which would work for your last example.

**Comment by gmourier** [comment]
Thanks @ManyTheFish! I confirm that it works with your proposal 🥳
