### ISSUE TITLE
Error while trying to compile

### ISSUE THREAD

**Issue by interlark** [meilisearch/milli#292]
```cargo run --release -- --db my-database.mdb -vvv --indexing-jobs 8```
<pre><font color="#4E9A06"><b>    Updating</b></font> crates.io index
<font color="#4E9A06"><b>    Updating</b></font> git repository `https://github.com/Kerollmops/grenad.git`
<font color="#4E9A06"><b>    Updating</b></font> git repository `https://github.com/Kerollmops/heed`
<font color="#4E9A06"><b>    Updating</b></font> git repository `https://github.com/meilisearch/Tokenizer.git`
<font color="#4E9A06"><b>    Updating</b></font> git repository `https://github.com/pest-parser/pest.git`
<font color="#4E9A06"><b>    Updating</b></font> git repository `https://github.com/meilisearch/lmdb-rs`
<font color="#CC0000"><b>error</b></font><b>:</b> failed to get `lmdb-rkv-sys` as a dependency of package `heed v0.12.0 (https://github.com/Kerollmops/heed?tag=v0.12.1#8e5dc6d7)`
    ... which is depended on by `milli v0.7.2 (/home/interlark/test/milli/milli)`

Caused by:
  failed to load source for dependency `lmdb-rkv-sys`

Caused by:
  Unable to update https://github.com/meilisearch/lmdb-rs#d0b50d02

Caused by:
  object not found - no match for id (d0b50d02938ee84e4e4372697ea991fe2a4cae3b); class=Odb (9); code=NotFound (-3)
</pre>

**Comment by Kerollmops** [comment]
Hey @interlark,

I am not quite sure why you get this error while trying to compile milli. That's strange that it happen because the CI is working great.

Would it be possible that you try again by updating the Rust compiler first ? `rustup update`

It would also be better to clone it from scratch too.

By the way have you tried using MeiliSearch directly instead of milli ? Milli is the internal library that is used by the new MeiliSearch engine v0.21. You can [try the latest alpha release](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0rc2) if you want and be careful to look at [the right documentation page](https://dev.doc.meilisearch.com).

**Comment by interlark** [comment]
Yeah, Cargo's upgrade did the tick (up to 1.53.0). Thank you.
