### ISSUE TITLE
Introduce a threshold to the asc/desc sorting criteria

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/milli#49]
The current Asc/Desc criteria choose between two ways of doing the job:
 1. If the number of candidates is lower or equal to 1000, it does a simple sort.
 2. If the number of candidates is bigger than 1000, it uses the facet database.

This number (1000) should better be a percentage of the total number of documents. It could be something like 0.1%. This way, we ensure that the best technique is used even if the database grows. #48 helps in retrieving the number of documents and, therefore, speedups computing a percentage.

**Comment by shekhirin** [comment]
Hi! I tried to resolve this issue in https://github.com/meilisearch/milli/pull/127.

Also I've found another place where such way of choosing an algorithm may be applicable, though it may be a miss since I'm new to the codebase.
https://github.com/meilisearch/milli/blob/38b6e8decd59013ef4e8cae4d7fef8ada80d6252/milli/src/search/facet/facet_distribution.rs#L25
https://github.com/meilisearch/milli/blob/38b6e8decd59013ef4e8cae4d7fef8ada80d6252/milli/src/search/facet/facet_distribution.rs#L210-L214
