### ISSUE TITLE
[QUESTION] mobile offline geocoding

### ISSUE THREAD

**Issue by farfromrefug** [meilisearch/milli#521]
I hope it is OK to ask question here.
I am investigating the possibility of using Milli for offline mobile geocoding
The idea is this :
- compile Milli for android and wrap.it through jni
- generate a pre indexed database of geocoding doxuments

Presented like this it seems doable. But there are some questions and would love to have the team opinion befaure rushing into this:
- i saw some numbers of 20mb memory usage with already indexed database. is that correct?
- wondering about the size the database would be. is there any comparison we can do between the json representation of the database and the database itself in terms of size?
- I know you have some Geo functions. could it handle filtering in a bbox ?
- does that seem like a good fit to you?

Thanks for that amazing project

**Comment by Kerollmops** [comment]
Hey @farfromrefug,

> * generate a pre indexed database of geocoding doxuments

What do you mean by pre-indexed? Is this something that milli will need to index or as it been already indexed by milli, and you are taking a snapshot (i.e. a copy of the already indexed file), here?

> * i saw some numbers of 20mb memory usage with already indexed database. is that correct?

Milli is entirely [based on LMDB](https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database), which is [a memory-mapped key-value store](https://web.archive.org/web/20210412154001/https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/). Memory mapping is a technology that let the OS choose between loading pages from the disk in memory based on the available amount of memory and the usage of the pages. The memory usage that you could see is either the Rust program itself when functioning or the virtual memory usage (due to the memory mapping). In short: the OS can use the whole memory if it evaluates that it is more performant to do so but it will automatically release it if other programs need it.

> * wondering about the size the database would be. is there any comparison we can do between the json representation of the database and the database itself in terms of size?

It is, unfortunately, very hard to evaluate the amount of disk space that will be used by the engine, you can probably do some tests and graph with your own data.

> * I know you have some Geo functions. could it handle filtering in a bbox ?

I don't think so, you should [look at the documentation](https://docs.meilisearch.com/learn/advanced/geosearch.html#geosearch), but [I think this is something that we wanted to implement at some point](https://github.com/meilisearch/product/discussions/431). You can use [the product repository to ask for specific features](https://github.com/meilisearch/product/).

> * does that seem like a good fit to you?

A good fit for doing searches without calling the HTTP server? Yeah, but keep in mind that it hasn't been developed for such use cases and therefore the documentation of this library is not very good. Milli is the core of Meilisearch and is kind of hidden inside.

**Comment by farfromrefug** [comment]
@Kerollmops First thank you for taking the time to answer me.

> What do you mean by pre-indexed? Is this something that milli will need to index or as it been already indexed by milli, and you are taking a snapshot (i.e. a copy of the already indexed file), here?

yes i am talking about a snapshot that i would prepare in advance and then push on the phone. The idea is for milli to have everything ready.

> A good fit for doing searches without calling the HTTP server? Yeah, but keep in mind that it hasn't been developed for such use cases and therefore the documentation of this library is not very good. Milli is the core of Meilisearch and is kind of hidden inside.

Yes the idea is to have something running as a lib and thus without an http server. Which is why i looked at milli directly. I know documentation is not "made for this" and i understand i would have to dig and test for myself.
This is also the reason i asked here first before going deep into it. 

I think i l close this issue as you answered my questions. Though i might be asking a few more questions in the future if i have a go at this ;)

Thanks again
