### ISSUE TITLE
`ubuntu-latest` is a better label for `20.04`

### ISSUE THREAD

**Issue by azzamsa** [meilisearch/milli#684]
Hi.

If we use `<OS>-latest` for all the runner labels. Wouldn't it be better to use `-latest` too for `ubuntu-20.04`?  
- https://github.com/actions/runner-images#available-images

One of the best advantages is that we don't need to change the runner version each time a new version is released or deprecated. 

Related PR:
- https://github.com/meilisearch/milli/pull/683

**Comment by curquiza** [comment]
Hello @azzamsa 
We would rather not use the `latest` versions of ubuntu since it can lead to CI breaking from one day to another without controlling it. We prefer working with fixed and specified versions.

Thanks for the suggestion but I'm sorry I have to close this issue since this is not something we want to do 😊
